# Dr. Francois Nguyen (Bio)

```{r}
tom <-c(21,32,45,67,32,21,2,1,4,12)
hist(tom)
```
## Impact statements:

Francois is a seasoned experienced teacher. He has been teaching for 40 years. Francois is well like by many of his students and colleagues at the college. He is very dedicated to help his students to overcome barriers and develop with their potentials so the can be successfully complete the training and obtain jobs. Francois is well known in his community he has helped many students from marginalized communities for education for employments throughout the years.
Francois embodies four components that considered critical for successful leadership in any education environment. These components are also critical for students’ success, experience, education, related skills, and student oriented personal and professional qualities. 
Experience:  Francois has forty-years classroom experience as an educator. He taught English as a Second Language, Mathematics, Chemistry, Human Relations, Cultural Awareness, Vietnamese, and Educational Methodology. His leadership abilities to help formulate educational programs, get other staff to buy into the plans and carry out the implementation of the strategies.  His leadership qualities assured desired results.
Education:  Mr. Nguyen completed his Ed D from St Mary’s University of Minnesota in 2007.   The education he received has provided him opportunities to explore a variety of educational philosophies and helped him develop his own based on current research and practices, supplemented by his personal experiences.  The success he has with students as he practices what he learns.  This is where Francois excels, education backed by real life experiences.  
Related Skills:  Mr. Nguyen have had opportunities to provide effective leadership.  He has participated in the evaluation of programs at various Minnesota colleges.  He has been a consultant on the proper way to recruit, hire and keep staff members of color.  He has served on numerous committees to develop educational strategies, evaluate programs, and successfully pass North Central accreditation.  All these opportunities required he demonstrate real leadership qualities.  It was always evident to many colleagues and students that he had the respect of his peers as well as administration.  His input was always appreciated, and his ideas and suggestions accepted.  An extra and valuable benefit to students at the college is Francois’ mastery of current educational technology.
Student Oriented Personal and Professional Qualities:  Although Mr. Nguyen has the required education, experience, and skills but it is his personal qualities that have always helped him succeed.  As his success with student achievement demonstrates, he values human relationships. To him it is not only about student graduation but also about the completion of all student goals, of all students.



